### ISSUE TITLE
[FEATURE]: Migrate from React CRA to NextJs 14 with App Router Typescript

### ISSUE THREAD

**Issue by raihanmd** [motionime/motionime-web#15]
## Description
The objective is to migrate our current React application, built with Create React App (CRA), to Next.js 14, utilizing its new App Directory Routing (App Router) and TypeScript. This migration is targeted to take full advantage of Next.js’s latest features like the new routing system, which simplifies pages and layouts handling, and enhances SEO and performance through built-in optimizations. TypeScript will be integrated to enforce type safety, improving the maintainability and robustness of our code.

## Steps to Implement
1. **Initialize a New Next.js 14 Project**: Set up a new project with Next.js 14 and TypeScript configurations.
2. **Understand and Implement App Router**: Explore the capabilities and configuration of the App Router in the `app/` directory. Adjust our current routing logic to fit this new model.
3. **Migrate Existing Components**: Adapt and migrate existing React components to the new structure, ensuring they comply with TypeScript types and Next.js optimizations.
4. **Update Build & Deployment Configurations**: Modify existing build processes and deployment strategies to accommodate Next.js.

## Additional Information
- Compatibility checks with current dependencies will be performed to ensure smooth integration.
- We will monitor the migration's impact on performance and SEO closely.

## Have you read the Code of Conduct?
Yes, I have read and agree to adhere to the [Code of Conduct](https://github.com/motionime/motionime-web/blob/main/CODE_OF_CONDUCT.md).

## Would you like to work on this issue?
Yes, I am ready to lead the migration to Next.js 14 with App Router and TypeScript.

### Do you want to work on this issue?

Yes

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/motionime/motionime-web/blob/main/CODE_OF_CONDUCT.md)

**Comment by raihanmd** [comment]
fix(docs): correct typo on previous commit

**Comment by irfankurniawansuthiono** [comment]
Ayo bang remake gogogogogo

**Comment by rhnas110** [comment]
@raihanmd semangat bang
![5zhk7t6pHIeQ](https://github.com/motionime/motionime-web/assets/51848196/fd30a4e0-f9bc-4dc7-a28d-d151f534c79d)

**Comment by raihanmd** [comment]
bentar ges rada delay kyknya ku ada urusan lain
